### PR TITLE
Fix databricks credentials and update GET endpoint

### LINKED ISSUE #136: Creating `dbt_cloud_databricks_credential` fails
Hi,

I am getting  `The request was invalid. Please double check the provided data and try again`:
```
╷
│ Error: POST url: https://cloud.getdbt.com/api/v3/accounts/x/projects/x/credentials/x/, status: 400, body: {"status":{"code":400,"is_success":false,"user_message":"The request was invalid. Please double check the provided data and try again.","developer_message":""},"data":{"credential_details":"{'fields': None, 'field_order': None} is not valid under any of the given schemas"}}
│ 
│   with dbt_cloud_databricks_credential.databricks,
│   on main.tf line 52, in resource "dbt_cloud_databricks_credential" "databricks":
│   52: resource "dbt_cloud_databricks_credential" "databricks" {
```

when trying to create

```

resource "dbt_cloud_databricks_credential" "databricks" {
  project_id  = local.project_id
  adapter_id  = dbt_cloud_connection.databricks.adapter_id
  num_threads = 16
  target_name = "default"
  token       = "<my-databricks-token>"
}

```

Seems that the post endpoint does not like the data being sent? I tried to look at the API docs in https://docs.getdbt.com/dbt-cloud/api-v2 but couldn't find the right endpoint to create credentials.. Not sure how to proceed.

### PR DESCRIPTION
**Pull request by b-per**
Fix #136 to allow management of Databricks credentials 

- fixes the issue
- update the GET endpoint to check a single credential rather than looping through them
- makes the test an acceptance test
- update the docs with an updated example

### Screenshot with the passing test:
SCR-20230530-rgue

### Breaking changes:
- fields for the resource have been added and optional/required fields have been changed
  - `num_threads` is removed as it is not relevant for credentials, only for jobs
  - added a field for `adapter` that needs to be set to `databricks` or `spark` to handle the different API calls

### CODE REVIEW

**Comment by b-per** [comment]
This PR also contains quite a bit of logic in the difference when creating/modifying credentials whether they are `spark` or `databricks`.

File: pkg/resources/databricks_credential.go [hunk 1]
```diff
@@ -9,6 +9,14 @@ import (
 	"github.com/gthesheep/terraform-provider-dbt-cloud/pkg/dbt_cloud"
 	"github.com/hashicorp/terraform-plugin-sdk/v2/diag"
 	"github.com/hashicorp/terraform-plugin-sdk/v2/helper/schema"
+	"github.com/hashicorp/terraform-plugin-sdk/v2/helper/validation"
+)
+
+var (
+	adapterTypes = []string{
+		"databricks",
+		"spark",
```
Comment (GtheSheep) [inline pkg/resources/databricks_credential.go:18]: Is spark linked to being Databricks only?

**Review by GtheSheep — APPROVED** [review]
Kinda have to go with it on Databricks as I can't test it 😅
